######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 26 20:52:11 2013
######################################################################

TEMPLATE = app
TARGET = mapgen
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lm
QT -= core gui debug

# Input
SOURCES += mapgen.c
