######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 4 16:30:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += opengl

# Input
HEADERS += blocks.h header.h screen.h thread.h world.h
SOURCES += blocks.cpp main.cpp screen.cpp thread.cpp world.cpp
