######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 10 21:22:56 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl
# Input
HEADERS += blocks.h header.h screen.h Shred.h thread.h world.h
SOURCES += blocks.cpp main.cpp screen.cpp Shred.cpp thread.cpp world.cpp
